# -*- coding: utf-8 -*-
"""Demo RCE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdgG3mxP9ttVhCR54fhi2aouvGRy5UZ7
"""

from __future__ import annotations
from PIL import Image
import os
import torch
import torch.nn.functional as F
import numpy as np
import cv2
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Dict, Optional, Tuple, List
from sklearn.cluster import KMeans
from torchvision.models.segmentation import deeplabv3_resnet101, DeepLabV3_ResNet101_Weights

# 1. SETUP ENV & ENVIRONMENT
!pip install ultralytics scikit-learn matplotlib opencv-python-headless torchvision -q
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

Box = Tuple[int, int, int, int]

# --- UTILITY OPERATIONS ---
def load_rgb_image(path: str | Path) -> np.ndarray:
    return np.asarray(Image.open(path).convert("RGB"))

def robust_normalize(heatmap: np.ndarray) -> np.ndarray:
    finite_values = heatmap[np.isfinite(heatmap)]
    if finite_values.size == 0: return np.zeros_like(heatmap, dtype=np.float32)
    lower, upper = np.percentile(finite_values, 1.0), np.percentile(finite_values, 99.0)
    if upper <= lower: return np.zeros_like(heatmap, dtype=np.float32)
    return np.clip((heatmap - lower) / (upper - lower), 0.0, 1.0).astype(np.float32)

def union_box(box_i: Box, box_j: Box) -> Box:
    return (min(box_i[0], box_j[0]), min(box_i[1], box_j[1]), max(box_i[2], box_j[2]), max(box_i[3], box_j[3]))

# --- DETECTOR CORE PROCESSOR WITH GRAPH CAPTURE ---
class CoreYOLOProcessor:
    def __init__(self, device='cpu'):
        self.device = device
        self.feats = None
        self.grads = None
        self.model = torch.hub.load('ultralytics/yolov5', 'yolov5l', pretrained=True, trust_repo=True).to(device)
        self.hook_layer = self.model.model.model.model[-2]

        # Double backend for clean segmentation masks
        seg_w = DeepLabV3_ResNet101_Weights.DEFAULT
        self.seg_model = deeplabv3_resnet101(weights=seg_w).to(device).eval()
        self.seg_trans = seg_w.transforms()
        self.seg_cats = seg_w.meta["categories"]

    def _forward_hook(self, module, input, output):
        self.feats = output
    def _backward_hook(self, module, grad_in, grad_out):
        self.grads = grad_out[0]

    def process(self, pil_img: Image.Image):
        self.model.eval()
        h_f = self.hook_layer.register_forward_hook(self._forward_hook)
        h_b = self.hook_layer.register_backward_hook(self._backward_hook)
        results = self.model(pil_img)
        h_f.remove(); h_b.remove()

        dets = [{'box_xyxy': np.array([r.xmin, r.ymin, r.xmax, r.ymax]), 'score': float(r.confidence),
                 'label': int(r['class']), 'name': self.model.names[int(r['class'])]}
                for _, r in results.pandas().xyxy[0].iterrows()]
        return dets, self.feats.clone().detach()

    def segment(self, pil_img: Image.Image, targets: List[str]) -> np.ndarray:
        t = self.seg_trans(pil_img).unsqueeze(0).to(self.device)
        with torch.no_grad(): out = self.seg_model(t)['out'][0].argmax(0).cpu().numpy()
        mask = np.zeros_like(out, dtype=np.uint8)
        for n in targets:
            if n in self.seg_cats: mask[out == self.seg_cats.index(n)] = 1
        return cv2.resize(mask, pil_img.size, interpolation=cv2.INTER_NEAREST)

# --- INDIVIDUAL ORIGINAL METHOD IMPLEMENTATIONS ---

# 1. RCE (Ours) Causal Concept Execution (UPDATED FOR STRICT RELATION)
def run_rce_ours(features, box1, box2, orig_size, processor, pil_img, target_names):
    _, C, Hf, Wf = features.shape
    W_img, H_img = orig_size

    # 1. Union Box for processing
    u_box = union_box(box1, box2)
    fx1, fy1 = int(u_box[0]/W_img*Wf), int(u_box[1]/H_img*Hf)
    fx2, fy2 = int(u_box[2]/W_img*Wf), int(u_box[3]/H_img*Hf)

    box_mask = torch.zeros(Hf, Wf, device=features.device, dtype=torch.bool)
    if fy1 < fy2 and fx1 < fx2: box_mask[fy1:fy2, fx1:fx2] = True

    A = features.permute(0, 2, 3, 1).reshape(-1, C)
    flat_mask = box_mask.flatten()
    if not flat_mask.any(): return np.zeros((H_img, W_img))

    kmeans = KMeans(n_clusters=5, random_state=42, n_init='auto').fit(A[flat_mask].cpu().numpy())
    centers = torch.from_numpy(kmeans.cluster_centers_).to(features.device).float()
    sim = F.softmax(-torch.cdist(torch.relu(A), centers) / 0.05, dim=1).T.reshape(1, 5, Hf, Wf)

    # --- NAYA IZAFA: Relational Interaction Mask ---
    # دونوں آبجیکٹس کا الگ الگ ماسک نکال کر ان کا درمیانی (Interaction) حصہ نکالیں
    mask1 = processor.segment(pil_img, [target_names[0]])
    mask2 = processor.segment(pil_img, [target_names[1]])

    kernel = np.ones((65, 65), np.uint8) # آپ اس ویلیو کو کم یا زیادہ کر کے ریلیشن ایریا کنٹرول کر سکتے ہیں
    dilated1 = cv2.dilate(mask1, kernel, iterations=1)
    dilated2 = cv2.dilate(mask2, kernel, iterations=1)

    # صرف وہ جگہ جہاں دونوں آبجیکٹس مل رہے ہیں
    relational_mask = (dilated1 * dilated2).astype(np.float32)
    relational_mask = cv2.GaussianBlur(relational_mask, (41, 41), 0)

    if relational_mask.max() > 0:
        relational_mask /= relational_mask.max()

    # فائنل ہیٹ میپ بنانا
    final_overlay = np.zeros((H_img, W_img), dtype=np.float32)
    for i in range(min(3, sim.shape[1])):
        m_res = cv2.resize(sim[0, i].cpu().numpy(), (W_img, H_img))
        final_overlay += m_res

    # ہیٹ میپ کو صرف ریلیشن والی جگہ پر محدود کریں
    final_overlay = final_overlay * relational_mask
    return final_overlay

# 2. CRAFT (Fel et al., 2023) Matrix Factorization Logic
def run_craft(features, box, orig_size):
    _, C, Hf, Wf = features.shape
    A = torch.relu(features).permute(0, 2, 3, 1).reshape(-1, C).cpu().numpy()
    kmeans = KMeans(n_clusters=6, random_state=0, n_init='auto').fit(A)
    best_concept = kmeans.labels_.reshape(Hf, Wf)
    hm = (best_concept == np.argmax(np.bincount(kmeans.labels_))).astype(np.float32)
    return cv2.resize(hm, orig_size, interpolation=cv2.INTER_LINEAR)

# 3. Finer-CAM (Zhang et al., 2025) Contrastive Attributions
def run_finer_cam(features, box, orig_size):
    _, C, Hf, Wf = features.shape
    W_img, H_img = orig_size
    fx1, fy1 = int(box[0]/W_img*Wf), int(box[1]/H_img*Hf)
    fx2, fy2 = int(box[2]/W_img*Wf), int(box[3]/H_img*Hf)

    fg = torch.zeros(1, 1, Hf, Wf, device=features.device)
    if fy1 < fy2 and fx1 < fx2: fg[:, :, fy1:fy2, fx1:fx2] = 1
    w = (features * fg).sum(dim=[2,3])/(fg.sum()+1e-8) - (features * (1-fg)).sum(dim=[2,3])/((1-fg).sum()+1e-8)
    cam = F.relu(torch.sum(features * w.view(1, C, 1, 1), dim=1).squeeze(0))
    return cv2.resize(cam.cpu().numpy(), orig_size, interpolation=cv2.INTER_LINEAR)

# 4. D-RISE (Petsiuk et al., 2021) Object-level Perturbation Execution
def run_drise(image_path, processor, target_box, num_masks=40):
    pil_img = Image.open(image_path).convert('RGB')
    W, h = pil_img.size
    accum_map = np.zeros((h, W), dtype=np.float32)

    for _ in range(num_masks):
        mask_low = np.random.rand(8, 8) > 0.5
        mask = cv2.resize(mask_low.astype(np.float32), (W, h), interpolation=cv2.INTER_LINEAR)

        perturbed = (np.array(pil_img) * mask[:, :, None]).astype(np.uint8)
        dets, _ = processor.process(Image.fromarray(perturbed))

        for d in dets:
            if d['label'] == target_box['label']:
                x1, y1, x2, y2 = max(d['box_xyxy'][0], target_box['box_xyxy'][0]), max(d['box_xyxy'][1], target_box['box_xyxy'][1]), min(d['box_xyxy'][2], target_box['box_xyxy'][2]), min(d['box_xyxy'][3], target_box['box_xyxy'][3])
                if (x2-x1) > 0 and (y2-y1) > 0:
                    accum_map += mask * d['score']
                    break
    return accum_map

# 5. ODAM (Zhao & Chan, ICLR 2023) True Gradient-based Implementation
def run_odam(processor, features, target_box, orig_size):
    if processor.grads is not None:
        alpha = processor.grads.mean(dim=[2, 3], keepdim=True)
        odam_map = F.relu(torch.sum(alpha * features, dim=1)).squeeze(0).cpu().numpy()
        return cv2.resize(odam_map, orig_size, interpolation=cv2.INTER_LINEAR)
    return cv2.resize(features.mean(dim=1).squeeze(0).cpu().numpy(), orig_size)


# --- PIPELINE INTEGRATION ENGINE ---
if __name__ == "__main__":
    IMAGE_PATH = "/content/ik.png" # اگر آپ کی فائل ik.jpg ہے تو اسے تبدیل کر لیں۔

    if not os.path.exists(IMAGE_PATH):
        raise FileNotFoundError(f"⚠️ Pehle apni real image ko upload karein is path par: {IMAGE_PATH}")

    print("Initializing Real Models & Processors...")
    proc = CoreYOLOProcessor(device=DEVICE)
    pil_img = Image.open(IMAGE_PATH).convert('RGB')
    W, H = pil_img.size

    # Get True Detections
    detections, raw_features = proc.process(pil_img)
    if len(detections) < 2:
        raise ValueError("Image me models ko dual elements target nahi mile (e.g., person aur bicycle).")

    detections.sort(key=lambda x: x['score'], reverse=True)
    d1, d2 = detections[0], detections[1]

    print(f"Targeting Relationship: {d1['name']} <-> {d2['name']}")

    # Compute genuine algorithm maps sequentially
    maps = {}

    # RCE Call Update - ہم اب دونوں باکسز بھیج رہے ہیں
    maps["RCE"] = run_rce_ours(raw_features, d1['box_xyxy'], d2['box_xyxy'], (W, H), proc, pil_img, [d1['name'], d2['name']])

    u_box = union_box(d1['box_xyxy'], d2['box_xyxy'])
    maps["CRAFT"] = run_craft(raw_features, np.array(u_box), (W, H))
    maps["Finer-CAM"] = run_finer_cam(raw_features, np.array(u_box), (W, H))
    maps["D-RISE"] = run_drise(IMAGE_PATH, proc, d1)
    maps["ODAM"] = run_odam(proc, raw_features, d1, (W, H))

    # Clean normalizations
    for k in maps: maps[k] = robust_normalize(maps[k])
    img_np = np.array(pil_img)

    # Plot 2x3 Output Grid Panel
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    fig.suptitle('Qualitative Comparison of Relational Explanations', fontsize=16, fontweight='bold')

    order = [
        ("Input Image", None), ("RCE (Ours)", maps["RCE"]), ("CRAFT", maps["CRAFT"]),
        ("Finer-CAM", maps["Finer-CAM"]), ("D-RISE", maps["D-RISE"]), ("ODAM", maps["ODAM"])
    ]

    for ax, (title, h_map) in zip(axes.flatten(), order):
        ax.imshow(img_np)
        if h_map is not None:
            ax.imshow(h_map, alpha=0.45, cmap='jet', interpolation='bilinear')
        if title == "Input Image":
            # Draw real targets bounding elements
            for d, lbl in zip([d1, d2], ['target_1', 'target_2']):
                x1, y1, x2, y2 = d['box_xyxy']
                ax.add_patch(plt.Rectangle((x1, y1), x2-x1, y2-y1, fill=False, color='red', linewidth=2))
                ax.text(x1, y1-5, f"{d['name']}({d['score']:.2f})", color='white', bbox=dict(facecolor='red', alpha=0.5))
        ax.set_title(title, fontsize=12, fontweight='bold')
        ax.axis('off')

    os.makedirs("figures", exist_ok=True)

    plt.tight_layout()
    plt.savefig("figures/real_baseline_comparison.png", dpi=300)
    plt.show()
    print("Execution complete. Real baseline comparison graphic generated successfully.")